<?php

use Illuminate\Database\Seeder;
use App\Models\HUD;
use App\Models\Block;

class BlockUrbanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $huds = HUD::get();

        $blocks = [
        	['name'=>'Ariyalur MPTY', 'hud_unique_code'=>'ariyalur00002'],	
['name'=>'Jayamkondam MPTY', 'hud_unique_code'=>'ariyalur00002'],	
['name'=>'Chengalpattu MPTY', 'hud_unique_code'=>'chengalpattu00004'],	
['name'=>'Pallavapuram MPTY', 'hud_unique_code'=>'chengalpattu00004'],	
['name'=>'Pammal MPTY', 'hud_unique_code'=>'chengalpattu00004'],	
['name'=>'Sembakkam MPTY', 'hud_unique_code'=>'chengalpattu00004'],	
['name'=>'Tambaram MPTY', 'hud_unique_code'=>'chengalpattu00004'],	
['name'=>'Madurantagam MPTY', 'hud_unique_code'=>'chengalpattu00004'],	
['name'=>'Anakaputhur MPTY', 'hud_unique_code'=>'chengalpattu00004'],	
['name'=>'Coimbatore CORPN.', 'hud_unique_code'=>'coimbatore00006'],	
['name'=>'Mettupalayam MPTY', 'hud_unique_code'=>'coimbatore00006'],	
['name'=>'Pollachi MPTY', 'hud_unique_code'=>'coimbatore00006'],	
['name'=>'Valparai MPTY', 'hud_unique_code'=>'coimbatore00006'],	
['name'=>'Chidambaram MPTY', 'hud_unique_code'=>'cuddalore00007'],	
['name'=>'Cuddalore MPTY', 'hud_unique_code'=>'cuddalore00007'],	
['name'=>'Panrutti MPTY', 'hud_unique_code'=>'cuddalore00007'],	
['name'=>'Virudachalam MPTY', 'hud_unique_code'=>'cuddalore00007'],	
['name'=>'Nellikuppam MPTY', 'hud_unique_code'=>'cuddalore00007'],	
['name'=>'Dharmapuri MPTY', 'hud_unique_code'=>'dharmapuri00008'],	
['name'=>'Dindigul CORPN.', 'hud_unique_code'=>'dindigul00009'],	
['name'=>'Palani MPTY', 'hud_unique_code'=>'palani00021'],	
['name'=>'Kodaikanal MPTY', 'hud_unique_code'=>'palani00021'],	
['name'=>'Ottanchathiram MPTY', 'hud_unique_code'=>'palani00021'],	
['name'=>'Erode CORPN.', 'hud_unique_code'=>'erode00010'],	
['name'=>'Gobichettipalayam ', 'hud_unique_code'=>'erode00010'],	
['name'=>'Bhavani MPTY', 'hud_unique_code'=>'erode00010'],	
['name'=>'Sathiyamangalam MPTY', 'hud_unique_code'=>'erode00010'],	
['name'=>'Kancheepuram MPTY', 'hud_unique_code'=>'kancheepuram00012'],	
['name'=>'Nagercoil CORPN.', 'hud_unique_code'=>'nagercoil00019'],	
['name'=>'Padmanabhapuram MPTY', 'hud_unique_code'=>'nagercoil00019'],	
['name'=>'Kuzhithurai MPTY', 'hud_unique_code'=>'nagercoil00019'],	
['name'=>'Colachel MPTY', 'hud_unique_code'=>'nagercoil00019'],	
['name'=>'Karur MPTY', 'hud_unique_code'=>'karur00013'],	
['name'=>'Kulithalai MPTY', 'hud_unique_code'=>'karur00013'],	
['name'=>'Hosur CORPN.', 'hud_unique_code'=>'krishnagiri00015'],	
['name'=>'Krishnagiri MPTY', 'hud_unique_code'=>'krishnagiri00015'],	
['name'=>'Madurai CORPN.', 'hud_unique_code'=>'madurai00016'],	
['name'=>'Thirumangalam MPTY', 'hud_unique_code'=>'madurai00016'],	
['name'=>'Melur MPTY', 'hud_unique_code'=>'madurai00016'],	
['name'=>'Usilampatti MPTY', 'hud_unique_code'=>'madurai00016'],	
['name'=>'Mayiladuthurai MPTY', 'hud_unique_code'=>'mayiladuthurai00017'],	
['name'=>'Sirkazhi MPTY', 'hud_unique_code'=>'mayiladuthurai00017'],	
['name'=>'Nagapattinam MPTY', 'hud_unique_code'=>'nagapattinam00018'],	
['name'=>'Vedaranyam MPTY', 'hud_unique_code'=>'nagapattinam00018'],	
['name'=>'Komarapalayam MPTY', 'hud_unique_code'=>'namakkal00020'],	
['name'=>'Namakkal MPTY', 'hud_unique_code'=>'namakkal00020'],	
['name'=>'Rasipuram MPTY', 'hud_unique_code'=>'namakkal00020'],	
['name'=>'Thiruchengode MPTY', 'hud_unique_code'=>'namakkal00020'],	
['name'=>'Pallipalayam MPTY', 'hud_unique_code'=>'namakkal00020'],	
['name'=>'Perambalur MPTY', 'hud_unique_code'=>'perambalur00023'],	
['name'=>'Aranthangi MPTY', 'hud_unique_code'=>'aranthangi00001'],	
['name'=>'Pudukottai MPTY', 'hud_unique_code'=>'pudukottai00025'],	
['name'=>'Paramakudi MPTY', 'hud_unique_code'=>'paramakudi00022'],	
['name'=>'Ramanathapuram MPTY', 'hud_unique_code'=>'ramanathapuram00026'],	
['name'=>'Keelakarai MPTY', 'hud_unique_code'=>'ramanathapuram00026'],	
['name'=>'Rameswaram MPTY', 'hud_unique_code'=>'ramanathapuram00026'],	
['name'=>'Walajapet MPTY', 'hud_unique_code'=>'ranipet00027'],	
['name'=>'Arakkonam MPTY', 'hud_unique_code'=>'ranipet00027'],	
['name'=>'Arcot MPTY', 'hud_unique_code'=>'ranipet00027'],	
['name'=>'Ranipet MPTY', 'hud_unique_code'=>'ranipet00027'],	
['name'=>'Narasingapuram MPTY', 'hud_unique_code'=>'athur00003'],	
['name'=>'Attur MPTY', 'hud_unique_code'=>'athur00003'],	
['name'=>'Edappadi MPTY', 'hud_unique_code'=>'salem00028'],	
['name'=>'Mettur MPTY', 'hud_unique_code'=>'salem00028'],	
['name'=>'Salem CORPN.', 'hud_unique_code'=>'salem00028'],	
['name'=>'Devakottai MPTY', 'hud_unique_code'=>'sivaganga00029'],	
['name'=>'Karaikudi  MPTY', 'hud_unique_code'=>'sivaganga00029'],	
['name'=>'Sivagangai MPTY', 'hud_unique_code'=>'sivaganga00029'],	
['name'=>'Sengottai MPTY', 'hud_unique_code'=>'tenkasi00031'],	
['name'=>'Kadayanallur MPTY', 'hud_unique_code'=>'tenkasi00031'],	
['name'=>'Puliangudi MPTY', 'hud_unique_code'=>'tenkasi00031'],	
['name'=>'Sankarankovil MPTY', 'hud_unique_code'=>'tenkasi00031'],	
['name'=>'Tenkasi MPTY', 'hud_unique_code'=>'tenkasi00031'],	
['name'=>'Kumbakonam MPTY', 'hud_unique_code'=>'thanjavur00032'],	
['name'=>'Pattukkottai MPTY', 'hud_unique_code'=>'thanjavur00032'],	
['name'=>'Thanjavur CORPN.', 'hud_unique_code'=>'thanjavur00032'],	
['name'=>'Gudalur (N)  MPTY', 'hud_unique_code'=>'thenilgiris00033'],	
['name'=>'Udhagamandalam MPTY', 'hud_unique_code'=>'thenilgiris00033'],	
['name'=>'Coonoor MPTY', 'hud_unique_code'=>'thenilgiris00033'],	
['name'=>'Nelliyalam MPTY', 'hud_unique_code'=>'thenilgiris00033'],	
['name'=>'Bodi MPTY', 'hud_unique_code'=>'theni00034'],	
['name'=>'Cumbum MPTY', 'hud_unique_code'=>'theni00034'],	
['name'=>'Theni-Allinagaram MPTY', 'hud_unique_code'=>'theni00034'],	
['name'=>'Periyakulam MPTY', 'hud_unique_code'=>'theni00034'],	
['name'=>'Chinnamanur MPTY', 'hud_unique_code'=>'theni00034'],	
['name'=>'Kovilpatti MPTY', 'hud_unique_code'=>'koilpatti00014'],	
['name'=>'Thoothukudi CORPN.', 'hud_unique_code'=>'tuticorin00042'],	
['name'=>'Kayalpattinam MPTY', 'hud_unique_code'=>'tuticorin00042'],	
['name'=>'Thuraiyur MPTY', 'hud_unique_code'=>'trichy00041'],	
['name'=>'Manaparai MPTY', 'hud_unique_code'=>'trichy00041'],	
['name'=>'Tiruchirappalli CORPN.', 'hud_unique_code'=>'trichy00041'],	
['name'=>'Ambasamudram MPTY', 'hud_unique_code'=>'tirunelveli00036'],	
['name'=>'Tirunelveli CORPN.', 'hud_unique_code'=>'tirunelveli00036'],	
['name'=>'Ambur  MPTY', 'hud_unique_code'=>'tirupathur00037'],	
['name'=>'Tirupathur MPTY', 'hud_unique_code'=>'tirupathur00037'],	
['name'=>'Vaniyambadi MPTY', 'hud_unique_code'=>'tirupathur00037'],	
['name'=>'Dharapuram MPTY', 'hud_unique_code'=>'tiruppur00038'],	
['name'=>'Tiruppur CORPN.', 'hud_unique_code'=>'tiruppur00038'],	
['name'=>'Udumalaipettai MPTY', 'hud_unique_code'=>'tiruppur00038'],	
['name'=>'Kangeyam MPTY', 'hud_unique_code'=>'tiruppur00038'],	
['name'=>'Palladam MPTY', 'hud_unique_code'=>'tiruppur00038'],	
['name'=>'Avadi CORPN.', 'hud_unique_code'=>'poonamallee00024'],	
['name'=>'Poonamallee MPTY', 'hud_unique_code'=>'poonamallee00024'],	
['name'=>'Thiruvallur MPTY', 'hud_unique_code'=>'tiruvallur00039'],	
['name'=>'Thiruverkadu MPTY', 'hud_unique_code'=>'tiruvallur00039'],	
['name'=>'Tiruttani MPTY', 'hud_unique_code'=>'tiruvallur00039'],	
['name'=>'Arani MPTY', 'hud_unique_code'=>'cheyyar00005'],	
['name'=>'Thiruvathipuram MPTY', 'hud_unique_code'=>'cheyyar00005'],	
['name'=>'Vandavasi MPTY', 'hud_unique_code'=>'cheyyar00005'],	
['name'=>'Tiruvannamalai MPTY', 'hud_unique_code'=>'tiruvannamalai00040'],	
['name'=>'Mannargudi MPTY', 'hud_unique_code'=>'thiruvarur00035'],	
['name'=>'Thiruvarur MPTY', 'hud_unique_code'=>'thiruvarur00035'],	
['name'=>'Tiruthuraipoondi MPTY', 'hud_unique_code'=>'thiruvarur00035'],	
['name'=>'Koothanallur MPTY', 'hud_unique_code'=>'thiruvarur00035'],	
['name'=>'Gudiyatham MPTY', 'hud_unique_code'=>'vellore00043'],	
['name'=>'Pernampet MPTY', 'hud_unique_code'=>'vellore00043'],	
['name'=>'Vellore CORPN.', 'hud_unique_code'=>'vellore00043'],	
['name'=>'Kallakurichi MPTY', 'hud_unique_code'=>'kallakurichi00011'],	
['name'=>'Tindivanam MPTY', 'hud_unique_code'=>'villupuram00044'],	
['name'=>'Villupuram MPTY', 'hud_unique_code'=>'villupuram00044'],	
['name'=>'Rajapalayam MPTY', 'hud_unique_code'=>'sivakasi00030'],	
['name'=>'Sivakasi MPTY', 'hud_unique_code'=>'sivakasi00030'],	
['name'=>'Srivilliputhur MPTY', 'hud_unique_code'=>'sivakasi00030'],	
['name'=>'Sattur MPTY', 'hud_unique_code'=>'sivakasi00030'],	
['name'=>'Aruppukottai MPTY', 'hud_unique_code'=>'virudhunagar00045'],	
['name'=>'Virudunagar MPTY', 'hud_unique_code'=>'virudhunagar00045'],	
        ];

foreach ($blocks as $key => $block) {
            $block['hud_id'] = $huds->where('unique_code', $block['hud_unique_code'])->first()->id ?? 0;
            $block['is_urban'] = _active();
            $block['status'] = _active();
            unset($block['hud_unique_code']);
            Block::create($block);
        }
    }
}
