<?php

use Illuminate\Database\Seeder;
use App\Models\Block;
use App\Models\PHC;

class PHCUrbanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $blocks = Block::get();

        $phcs = [

        	['name'=>'UPHC-Ambasamudram', 'block_unique_code'=>'ambasamudrammpty00483'],
['name'=>'UPHC-Ambur', 'block_unique_code'=>'amburmpty00485'],
['name'=>'UPHC-Kaspa B', 'block_unique_code'=>'amburmpty00485'],
['name'=>'UPHC-Anakaputhur', 'block_unique_code'=>'anakaputhurmpty00400'],
['name'=>'UPHC-Arakkonam', 'block_unique_code'=>'arakkonammpty00449'],
['name'=>'UPHC-Arani', 'block_unique_code'=>'aranimpty00498'],
['name'=>'UPHC-Aranthangi', 'block_unique_code'=>'aranthangimpty00442'],
['name'=>'UPHC-Arcot', 'block_unique_code'=>'arcotmpty00450'],
['name'=>'UPHC-Ariyalur', 'block_unique_code'=>'ariyalurmpty00392'],
['name'=>'UPHC-Aruppukottai', 'block_unique_code'=>'aruppukottaimpty00516'],
['name'=>'UPHC-Attur', 'block_unique_code'=>'atturmpty00453'],
['name'=>'UPHC-Paruthipattu', 'block_unique_code'=>'avadicorpn00493'],
['name'=>'UPHC-Villinjiambakkam', 'block_unique_code'=>'avadicorpn00493'],
['name'=>'UPHC-Thirumullaivoyal', 'block_unique_code'=>'avadicorpn00493'],
['name'=>'UPHC-Mittinamallee', 'block_unique_code'=>'avadicorpn00493'],
['name'=>'UPHC-Thandurai', 'block_unique_code'=>'avadicorpn00493'],
['name'=>'UPHC-Periyar Nagar', 'block_unique_code'=>'avadicorpn00493'],
['name'=>'UPHC-Cholambedu', 'block_unique_code'=>'avadicorpn00493'],
['name'=>'UPHC-Bhavani', 'block_unique_code'=>'bhavanimpty00417'],
['name'=>'UPHC-Bodinayakkanur', 'block_unique_code'=>'bodimpty00472'],
['name'=>'UPHC-Chengalpattu', 'block_unique_code'=>'chengalpattumpty00394'],
['name'=>'UPHC-Chidambaram', 'block_unique_code'=>'chidambarammpty00405'],
['name'=>'UPHC-Chinnamanur', 'block_unique_code'=>'chinnamanurmpty00476'],
['name'=>'UPHC-Srinivasapuram (CTM Home)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Ramanathapuram', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Ganapathy', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Jail Road', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Saibaba Colony (KK Pudur)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Bharathi Park Road-II (MM Home)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Pothanur (Nanjundapuram)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Sukkarawarpet (Pattunool)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Peelamedu', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Raja Street', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Nehru St (Rathanpuri)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Gandhi Park (RK Bai)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-PN Pudur (SN Palayam)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Selvapuram', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-RS Puram (SLM Home)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Sowripalayam', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Telungupalayam', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Uppilipalayam', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Vysial Street (VVM Home)', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Singanallur', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Ganapathi Managar', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Vilankurichi', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Neelikonampalayam', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Thondamuthur', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Kalveeranpalayam', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Thudiyalur', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Pothanur', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Vellakinar', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Kuniamuthur', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Kurichi', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Vadavalli', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Goundanpalayam', 'block_unique_code'=>'coimbatorecorpn00401'],
['name'=>'UPHC-Colachel', 'block_unique_code'=>'colachelmpty00423'],
['name'=>'UPHC-Coonoor', 'block_unique_code'=>'coonoormpty00470'],
['name'=>'UPHC-Cuddalore OT', 'block_unique_code'=>'cuddalorempty00406'],
['name'=>'UPHC-Pudupalayam', 'block_unique_code'=>'cuddalorempty00406'],
['name'=>'UPHC-Thirupapuliyur', 'block_unique_code'=>'cuddalorempty00406'],
['name'=>'UPHC-Cumbum', 'block_unique_code'=>'cumbummpty00473'],
['name'=>'UPHC-Devakottai', 'block_unique_code'=>'devakottaimpty00457'],
['name'=>'UPHC-Dharapuram', 'block_unique_code'=>'dharapurammpty00488'],
['name'=>'UPHC-Dharmapuri', 'block_unique_code'=>'dharmapurimpty00410'],
['name'=>'UPHC-Kamala Nehru', 'block_unique_code'=>'dindigulcorpn00411'],
['name'=>'UPHC-Marianathapuram', 'block_unique_code'=>'dindigulcorpn00411'],
['name'=>'UPHC-Savariyarpalayam', 'block_unique_code'=>'dindigulcorpn00411'],
['name'=>'UPHC-Palani Road', 'block_unique_code'=>'dindigulcorpn00411'],
['name'=>'UPHC-Edappadi', 'block_unique_code'=>'edappadimpty00454'],
['name'=>'UPHC-Surampatti', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-BP Agraharam', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Periyasemur', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Suriyampalayam', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Veerappanchatiram', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Karungalpalayam', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Agathiar', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Rajajipuram', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Gandhiji Road', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Nethaji Road', 'block_unique_code'=>'erodecorpn00415'],
['name'=>'UPHC-Gobichettipalayam', 'block_unique_code'=>'gobichettipalayam00416'],
['name'=>'UPHC-Gudalur(N)', 'block_unique_code'=>'gudalurnmpty00468'],
['name'=>'UPHC-Gudiyatham', 'block_unique_code'=>'gudiyathammpty00506'],
['name'=>'UPHC-Nellorpettai (Santhapettai)', 'block_unique_code'=>'gudiyathammpty00506'],
['name'=>'UPHC-Mookandapalli', 'block_unique_code'=>'hosurcorpn00426'],
['name'=>'UPHC-Appavu Nagar', 'block_unique_code'=>'hosurcorpn00426'],
['name'=>'UPHC-Seetharam Nagar', 'block_unique_code'=>'hosurcorpn00426'],
['name'=>'UPHC-Avalapalli', 'block_unique_code'=>'hosurcorpn00426'],
['name'=>'UPHC-Jayamkondam', 'block_unique_code'=>'jayamkondammpty00393'],
['name'=>'UPHC-Melakadayanallur', 'block_unique_code'=>'kadayanallurmpty00461'],
['name'=>'UPHC-Krishnapuram', 'block_unique_code'=>'kadayanallurmpty00461'],
['name'=>'UPHC-Kallakurichi', 'block_unique_code'=>'kallakurichimpty00509'],
['name'=>'UPHC-Sevilimedu', 'block_unique_code'=>'kancheepurammpty00419'],
['name'=>'UPHC-Panjupettai', 'block_unique_code'=>'kancheepurammpty00419'],
['name'=>'UPHC-Pillayarpalayam', 'block_unique_code'=>'kancheepurammpty00419'],
['name'=>'UPHC-Chinna Kancheepuram', 'block_unique_code'=>'kancheepurammpty00419'],
['name'=>'UPHC-Nathampettai', 'block_unique_code'=>'kancheepurammpty00419'],
['name'=>'UPHC-Kangeyam', 'block_unique_code'=>'kangeyammpty00491'],
['name'=>'UPHC-Senjai', 'block_unique_code'=>'karaikudimpty00458'],
['name'=>'UPHC-Muthupattinam', 'block_unique_code'=>'karaikudimpty00458'],
['name'=>'UPHC-Karur', 'block_unique_code'=>'karurmpty00424'],
['name'=>'UPHC-Inam Karur', 'block_unique_code'=>'karurmpty00424'],
['name'=>'UPHC-Thanthoni', 'block_unique_code'=>'karurmpty00424'],
['name'=>'UPHC-Azad Road', 'block_unique_code'=>'karurmpty00424'],
['name'=>'UPHC-Kayalpattinam', 'block_unique_code'=>'kayalpattinammpty00479'],
['name'=>'UPHC-Keelakarai', 'block_unique_code'=>'keelakaraimpty00446'],
['name'=>'UPHC-Kodaikanal', 'block_unique_code'=>'kodaikanalmpty00413'],
['name'=>'UPHC-Komarapalayam', 'block_unique_code'=>'komarapalayammpty00436'],
['name'=>'UPHC-Marakkalkaadu', 'block_unique_code'=>'komarapalayammpty00436'],
['name'=>'UPHC-Koothanallur', 'block_unique_code'=>'koothanallurmpty00505'],
['name'=>'UPHC-Oorani Street', 'block_unique_code'=>'kovilpattimpty00477'],
['name'=>'UPHC-Sriram Nagar', 'block_unique_code'=>'kovilpattimpty00477'],
['name'=>'UPHC-Krishnagiri', 'block_unique_code'=>'krishnagirimpty00427'],
['name'=>'UPHC-Kulithalai', 'block_unique_code'=>'kulithalaimpty00425'],
['name'=>'UPHC-Kamaraj Road', 'block_unique_code'=>'kumbakonammpty00465'],
['name'=>'UPHC-Melakauveri', 'block_unique_code'=>'kumbakonammpty00465'],
['name'=>'UPHC-Kumbeswaran South', 'block_unique_code'=>'kumbakonammpty00465'],
['name'=>'UPHC-Kuzhithurai', 'block_unique_code'=>'kuzhithuraimpty00422'],
['name'=>'UPHC-Thiruparangundram', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Anaiyur', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Avaniyapuram', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Aruldosspuram', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Sellur', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Narimedu', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-B.B.Kulam', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-K.Pudur', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Sathamangalam', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Munichalai', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Balarangapuram', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Anupanadi', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Villapuram', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-MK Puram', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Bykara', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Fatima nagar', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Thideer nagar', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Ansarinagar', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Puthuthoppu', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Annathoppu', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Subramaniapuram', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Therkuvasal', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Kodikulam', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Vandiyur', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Chinthamani', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Thirunagar', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Virattipathu', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Karisalkulam', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Thirupalai', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Masthanpatti', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Solai Alagupuram', 'block_unique_code'=>'maduraicorpn00428'],
['name'=>'UPHC-Madurantagam', 'block_unique_code'=>'madurantagammpty00399'],
['name'=>'UPHC-Manaparai', 'block_unique_code'=>'manaparaimpty00481'],
['name'=>'UPHC-Mannargudi', 'block_unique_code'=>'mannargudimpty00502'],
['name'=>'UPHC-Mayiladuthurai', 'block_unique_code'=>'mayiladuthuraimpty00432'],
['name'=>'UPHC-Melur', 'block_unique_code'=>'melurmpty00430'],
['name'=>'UPHC-Mettupalayam', 'block_unique_code'=>'mettupalayammpty00402'],
['name'=>'UPHC-Mettur', 'block_unique_code'=>'metturmpty00455'],
['name'=>'UPHC-Nagore', 'block_unique_code'=>'nagapattinammpty00434'],
['name'=>'UPHC-Nagapattinam Marunthukothalam', 'block_unique_code'=>'nagapattinammpty00434'],
['name'=>'UPHC-Vattavilai', 'block_unique_code'=>'nagercoilcorpn00420'],
['name'=>'UPHC-Krishnankovil', 'block_unique_code'=>'nagercoilcorpn00420'],
['name'=>'UPHC-Vadiveesvaram', 'block_unique_code'=>'nagercoilcorpn00420'],
['name'=>'UPHC-Vadassery', 'block_unique_code'=>'nagercoilcorpn00420'],
['name'=>'UPHC-Thollavilai', 'block_unique_code'=>'nagercoilcorpn00420'],
['name'=>'UPHC-Namakkal', 'block_unique_code'=>'namakkalmpty00437'],
['name'=>'UPHC-Mudalaipatti', 'block_unique_code'=>'namakkalmpty00437'],
['name'=>'UPHC-Narasingapuram', 'block_unique_code'=>'narasingapurammpty00452'],
['name'=>'UPHC-Nellikuppam', 'block_unique_code'=>'nellikuppammpty00409'],
['name'=>'UPHC-Nelliyalam', 'block_unique_code'=>'nelliyalammpty00471'],
['name'=>'UPHC-Ottanchathiram', 'block_unique_code'=>'ottanchathirammpty00414'],
['name'=>'UPHC-Padmanabhapuram', 'block_unique_code'=>'padmanabhapurammpty00421'],
['name'=>'UPHC-Palani', 'block_unique_code'=>'palanimpty00412'],
['name'=>'UPHC-Palladam', 'block_unique_code'=>'palladammpty00492'],
['name'=>'UPHC-Zamin Pallavapuram', 'block_unique_code'=>'pallavapurammpty00395'],
['name'=>'UPHC-Keezhkattalai', 'block_unique_code'=>'pallavapurammpty00395'],
['name'=>'UPHC-Haridosspuram', 'block_unique_code'=>'pallavapurammpty00395'],
['name'=>'UPHC-Kulakarai Street', 'block_unique_code'=>'pallavapurammpty00395'],
['name'=>'UPHC-Pallipalayam', 'block_unique_code'=>'pallipalayammpty00440'],
['name'=>'UPHC-Pammal', 'block_unique_code'=>'pammalmpty00396'],
['name'=>'UPHC-Panrutti', 'block_unique_code'=>'panruttimpty00407'],
['name'=>'UPHC-Emaneswaram', 'block_unique_code'=>'paramakudimpty00444'],
['name'=>'UPHC-Bharathiyar Park', 'block_unique_code'=>'paramakudimpty00444'],
['name'=>'UPHC-Pattukkottai', 'block_unique_code'=>'pattukkottaimpty00466'],
['name'=>'UPHC-Perambalur', 'block_unique_code'=>'perambalurmpty00441'],
['name'=>'UPHC-Periyakulam', 'block_unique_code'=>'periyakulammpty00475'],
['name'=>'UPHC-Pernampet', 'block_unique_code'=>'pernampetmpty00507'],
['name'=>'UPHC-Vadugapalayam', 'block_unique_code'=>'pollachimpty00403'],
['name'=>'UPHC-Kamatchi Nagar', 'block_unique_code'=>'pollachimpty00403'],
['name'=>'UPHC-Poonamallee', 'block_unique_code'=>'poonamalleempty00494'],
['name'=>'UPHC-Kamarajapuram', 'block_unique_code'=>'pudukottaimpty00443'],
['name'=>'UPHC-Kovilpatti', 'block_unique_code'=>'pudukottaimpty00443'],
['name'=>'UPHC-Puliangudi', 'block_unique_code'=>'puliangudimpty00462'],
['name'=>'UPHC-Madasamy Koil St', 'block_unique_code'=>'rajapalayammpty00512'],
['name'=>'UPHC-TP Mills Road', 'block_unique_code'=>'rajapalayammpty00512'],
['name'=>'UPHC-Ramanathapuram', 'block_unique_code'=>'ramanathapurammpty00445'],
['name'=>'UPHC-Rameswaram', 'block_unique_code'=>'rameswarammpty00447'],
['name'=>'UPHC-Ranipet', 'block_unique_code'=>'ranipetmpty00451'],
['name'=>'UPHC-Rasipuram', 'block_unique_code'=>'rasipurammpty00438'],
['name'=>'UPHC-Arisipalayam', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Kumarasamipatti (Hasthampatti)', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Ponnampet', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Ammapet', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Kitchipalayam', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Shevvapet', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Dadagapatty', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Subramaniya Nagar', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Gugai', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Karungalpatti', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Anna Hospital', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-NGGO Colony', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Reddiyoor', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Old Sooramangalam', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Annadhanapatty', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Pallapatty', 'block_unique_code'=>'salemcorpn00456'],
['name'=>'UPHC-Sankarankovil', 'block_unique_code'=>'sankarankovilmpty00463'],
['name'=>'UPHC-Sathiyamangalam', 'block_unique_code'=>'sathiyamangalammpty00418'],
['name'=>'UPHC-Sattur', 'block_unique_code'=>'satturmpty00515'],
['name'=>'UPHC-Sembakkam', 'block_unique_code'=>'sembakkammpty00397'],
['name'=>'UPHC-Sengottai', 'block_unique_code'=>'sengottaimpty00460'],
['name'=>'UPHC-Sirkazhi', 'block_unique_code'=>'sirkazhimpty00433'],
['name'=>'UPHC-Sivagangai', 'block_unique_code'=>'sivagangaimpty00459'],
['name'=>'UPHC-Sivakasi', 'block_unique_code'=>'sivakasimpty00513'],
['name'=>'UPHC-Srivilliputhur', 'block_unique_code'=>'srivilliputhurmpty00514'],
['name'=>'UPHC-East Tambaram', 'block_unique_code'=>'tambarammpty00398'],
['name'=>'UPHC-Patel Nagar (West Tambaram)', 'block_unique_code'=>'tambarammpty00398'],
['name'=>'UPHC-Renganathapuram', 'block_unique_code'=>'tambarammpty00398'],
['name'=>'UPHC-Tenkasi', 'block_unique_code'=>'tenkasimpty00464'],
['name'=>'UPHC-Karanthai', 'block_unique_code'=>'thanjavurcorpn00467'],
['name'=>'UPHC-Srinivasapuram', 'block_unique_code'=>'thanjavurcorpn00467'],
['name'=>'UPHC-Maharnombuchavadi', 'block_unique_code'=>'thanjavurcorpn00467'],
['name'=>'UPHC-Kallukulam', 'block_unique_code'=>'thanjavurcorpn00467'],
['name'=>'UPHC-Theni', 'block_unique_code'=>'theni-allinagarammpty00474'],
['name'=>'UPHC-Bommayagoundanpatti', 'block_unique_code'=>'theni-allinagarammpty00474'],
['name'=>'UPHC-Thiruchengode', 'block_unique_code'=>'thiruchengodempty00439'],
['name'=>'UPHC-Seetharamapalayam', 'block_unique_code'=>'thiruchengodempty00439'],
['name'=>'UPHC-Thirumangalam', 'block_unique_code'=>'thirumangalammpty00429'],
['name'=>'UPHC-Thiruvallur', 'block_unique_code'=>'thiruvallurmpty00495'],
['name'=>'UPHC-Thiruvarur', 'block_unique_code'=>'thiruvarurmpty00503'],
['name'=>'UPHC-Thiruvathipuram', 'block_unique_code'=>'thiruvathipurammpty00499'],
['name'=>'UPHC-Thiruverkadu', 'block_unique_code'=>'thiruverkadumpty00496'],
['name'=>'UPHC-Lourdammalpuram', 'block_unique_code'=>'thoothukudicorpn00478'],
['name'=>'UPHC-Mullaikadu', 'block_unique_code'=>'thoothukudicorpn00478'],
['name'=>'UPHC-Fathima Nagar', 'block_unique_code'=>'thoothukudicorpn00478'],
['name'=>'UPHC-Tharuvai Road', 'block_unique_code'=>'thoothukudicorpn00478'],
['name'=>'UPHC-Therespuram', 'block_unique_code'=>'thoothukudicorpn00478'],
['name'=>'UPHC-P&T colony', 'block_unique_code'=>'thoothukudicorpn00478'],
['name'=>'UPHC-Ganesh Nagar', 'block_unique_code'=>'thoothukudicorpn00478'],
['name'=>'UPHC-Thuraiyur', 'block_unique_code'=>'thuraiyurmpty00480'],
['name'=>'UPHC-Tindivanam', 'block_unique_code'=>'tindivanammpty00510'],
['name'=>'UPHC-Kattur', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Thiruverumbur', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Periyamilaguparai', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Beemanagar', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Theppakulam', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-EB Road', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Thennur', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Subramaniyapuram', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Srirangam', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Woraiyur', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Hiruthayapuram', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Kamaraj Nagar', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-M.K.Kottai', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Tiruvanaikovil', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Beerangikulam', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Edamalaipatti pudur', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Ramalinganagar', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Woraiyur Gandhipuram', 'block_unique_code'=>'tiruchirappallicorpn00482'],
['name'=>'UPHC-Pettai', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Palayapettai', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Pattapathu', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-MV Puram', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Kokkirakulam', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Samathanapuram', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Perumalpuram', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Melapalayam', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Palayamkottai', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Thatchanallur', 'block_unique_code'=>'tirunelvelicorpn00484'],
['name'=>'UPHC-Tirupattur', 'block_unique_code'=>'tirupathurmpty00486'],
['name'=>'UPHC-Velampalayam', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Nallur', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Nesavalar Colony', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-KVR Nagar', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-TSK Colony', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Old Market Road (PRM Home)', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Mettupalayam', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-LRGR', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Soosaiyapuram', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Neruparichal', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Guruvayurappan Nagar', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-T. Mannarai', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Periyandipalayam', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Veerapandi', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Sundamedu', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Kovilvazhi', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Anna Nesavalar Colony', 'block_unique_code'=>'tiruppurcorpn00489'],
['name'=>'UPHC-Tiruthuraipoondi', 'block_unique_code'=>'tiruthuraipoondimpty00504'],
['name'=>'UPHC-Tiruttani', 'block_unique_code'=>'tiruttanimpty00497'],
['name'=>'UPHC-Annanagar', 'block_unique_code'=>'tiruvannamalaimpty00501'],
['name'=>'UPHC-Central', 'block_unique_code'=>'tiruvannamalaimpty00501'],
['name'=>'UPHC-Kilnathur', 'block_unique_code'=>'tiruvannamalaimpty00501'],
['name'=>'UPHC-Udhagamandalam', 'block_unique_code'=>'udhagamandalammpty00469'],
['name'=>'UPHC-Udumalaipettai', 'block_unique_code'=>'udumalaipettaimpty00490'],
['name'=>'UPHC-Usilampatti', 'block_unique_code'=>'usilampattimpty00431'],
['name'=>'UPHC-Valparai', 'block_unique_code'=>'valparaimpty00404'],
['name'=>'UPHC-Mudis Nagar', 'block_unique_code'=>'valparaimpty00404'],
['name'=>'UPHC-Sholayar Nagar', 'block_unique_code'=>'valparaimpty00404'],
['name'=>'UPHC-Vandavasi', 'block_unique_code'=>'vandavasimpty00500'],
['name'=>'UPHC-Vaniyambadi', 'block_unique_code'=>'vaniyambadimpty00487'],
['name'=>'UPHC-Newtown', 'block_unique_code'=>'vaniyambadimpty00487'],
['name'=>'UPHC-Vedaranyam', 'block_unique_code'=>'vedaranyammpty00435'],
['name'=>'UPHC-Dharapadavedu', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Pallikuppam', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Sathuvachary', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Alamelumangapuram', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Konavattam', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Ambedkar Nagar', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Saidapet', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Lakshmipuram', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Kaspa', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Thorapadi', 'block_unique_code'=>'vellorecorpn00508'],
['name'=>'UPHC-Villupuram', 'block_unique_code'=>'villupurammpty00511'],
['name'=>'UPHC-Keezhperumbakkam', 'block_unique_code'=>'villupurammpty00511'],
['name'=>'UPHC-Virudhachalam', 'block_unique_code'=>'virudachalammpty00408'],
['name'=>'UPHC-Virudhunagar', 'block_unique_code'=>'virudunagarmpty00517'],
['name'=>'UPHC-Walajapet', 'block_unique_code'=>'walajapetmpty00448'],

        ];

        foreach ($phcs as $key => $phc) {
            $phc['block_id'] = $blocks->where('unique_code', $phc['block_unique_code'])->first()->id ?? 0;
            $phc['status'] = _active();
            $phc['is_urban'] = _active();
            unset($phc['block_unique_code']);
            PHC::create($phc);
        }
    }
}


